### PR TITLE
Docs updates for credentials for CFs

### PR DESCRIPTION
**Pull request by teddyking**
Hey docs team, here's the latest bunch of docs updates.

These changes reflect the way we expect users to install and register Cloud Foundries with pdc.

Thanks!

### CODE REVIEW

**Comment by snneji** [comment]
Hi @teddyking! Before merging this, is this change intended for the 0.3 or the 0.4 docs?

**Comment by teddyking** [comment]
This is for the 0.4 docs thanks!

**Comment by teddyking** [comment]
Ah sorry I was mistaken, these changes will actually need to be in the next release, which we are now planning to make version 0.3.1 (we will be skipping version 0.3).

**Comment by snneji** [comment]
Thanks - I'll merge them now

**Pull request merged**
